name : My first github implementation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setupnode@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm start
          
    